### ISSUE TITLE
Refuses logins less then 22 characters

### ISSUE THREAD

**Issue by bitcoins1g** [pacatum/Helmbet-RPS#1]
Helmbet refuses to allow logins less then 22 characters even though they are allowed by the network and allowed by the paperwallet faucet. This leads to confusion on the part of the user who comes to telegram and says they can't login and the software is broken.

**Comment by pacatum** [comment]
Core Wallet supports minimum of 22 characters, that's why HelmBet app was built same way. Paperwallet is not official application and is only used temporally to support BETA testing. Please read release note that advises to use 22 characters as a password.
