### ISSUE TITLE
Can't continue to Add Friends

### ISSUE THREAD

**Issue by kstkeyes** [pacatum/Helmbet-RPS#10]
In the ADD FRIENDS section once you get to a certain # of added friends, the area isn't scrollable and you can no longer see the drop down. Screenshot attached.

<img width="1440" alt="screen shot 2017-09-13 at 3 43 36 pm" src="https://user-images.githubusercontent.com/1774215/30394759-799b7ec8-989a-11e7-9190-54869b75f0af.png">

**Comment by pacatum** [comment]
Thanks for the feedback. Issue will be fixed in next versions.

**Comment by pacatum** [comment]
Fixed in https://github.com/pacatum/Helmbet-RPS/releases/tag/v0.2b
