### ISSUE TITLE
Grammar on Create a Game page

### ISSUE THREAD

**Issue by SahkanDesertHawk** [pacatum/Helmbet-RPS#14]
Says: "Or it is not?" should say: "Or is it not?"

**Comment by SahkanDesertHawk** [comment]
And under "Add friend"
Change: "the Private" to "a Private"

**Comment by SahkanDesertHawk** [comment]
After Creating the tournament, on the pop up: "created&joined!" should be "created & joined!"

**Comment by SahkanDesertHawk** [comment]
I would also replace "THANKS!" on the button with "OK"

**Comment by pacatum** [comment]
Fixed with https://github.com/pacatum/Helmbet-RPS/releases/tag/v0.3b
