### ISSUE TITLE
Peerplays label is mispelled

### ISSUE THREAD

**Issue by robrigo** [pacatum/Helmbet-RPS#16]
Launching the Mac v1.0 release, there is a typo in Peerplays on the "Get Peerplays Wallet" button:

<img width="606" alt="screen shot 2017-10-12 at 12 29 27 pm" src="https://user-images.githubusercontent.com/590263/31507607-389976b2-af49-11e7-9c76-58393000e99f.png">

**Comment by pacatum** [comment]
Fixed in version https://github.com/pacatum/Helmbet-RPS/releases/tag/v1.1
