### ISSUE TITLE
Login button does nothing on Helmbet-RPS v1.0 app for Mac

### ISSUE THREAD

**Issue by robrigo** [pacatum/Helmbet-RPS#17]
I put a username and password into the helmbet login, yet clicking the login button or hitting "enter" to submit the form doesn't do anything, like show an error message or authenticate:

<img width="508" alt="screen shot 2017-10-12 at 1 29 26 pm" src="https://user-images.githubusercontent.com/590263/31510022-6b08ee54-af51-11e7-9556-7a8041e1a22b.png">

**Comment by pacatum** [comment]
If Login Buton is not highlighted in blue (not active) that means you might've entered incorrect format of login name or password. Please make sure you are entering a minimum of 22 symbols as a Password, username should have at least one dash or number.

**Comment by robrigo** [comment]
My password is long enough, and "robrigo" is a valid name registered on the blockchain. The account registration faucet used by the Peerplays Core GUI wallet will only allow you to register non-premium names (i.e. names with a number or dash), however it is possible to register premium names on the Peerplays blockchain such as "robrigo" from a CLI wallet. 

As you can see on this block explorer, "robrigo" is a valid account name: https://peerplaysdb.com/@robrigo

So it appears account name validation needs to be changed to accept premium names.

**Comment by designsters** [comment]
Thanks for clarification, we'll fix validation issue as a top priority!

**Comment by pacatum** [comment]
Thanks for clarification, we'll fix validation issue as a top priority!

**Comment by robrigo** [comment]
Thank you, I would also caution against requiring 22 characters for password, as that is not a limit enforced by the Peerplays blockchain. It could be enforced by account registration faucets but nothing guarantees all accounts will have a 22 character or longer password.

**Comment by pacatum** [comment]
Noted! Exact minimum will be confirmed and applied to validation as well.

**Comment by pacatum** [comment]
Fixed in version https://github.com/pacatum/Helmbet-RPS/releases/tag/v1.1
