### ISSUE TITLE
Current balance should be displayed more prominently

### ISSUE THREAD

**Issue by bitcoins1g** [pacatum/Helmbet-RPS#2]
Users have to dig through the menu to see the current balance. It would be better to display that information to the users on the right hand side where it says "Filter Your Search". Perhaps also include it as a table with the results of the last 5-10 game results.

**Comment by pacatum** [comment]
Thanks for the feedback, issue will be reviewed by our designer.

**Comment by SahkanDesertHawk** [comment]
Just to add to this: The winnings are not displayed and the blockchained reflected the .05 PPY fee but it did not reflect any winnings. Seemed to me that it should be .08PPY per round?

**Comment by pacatum** [comment]
Fixed with https://github.com/pacatum/Helmbet-RPS/releases/tag/v0.3b
