### ISSUE TITLE
Tournament History not displaying

### ISSUE THREAD

**Issue by kstkeyes** [pacatum/Helmbet-RPS#8]
When I click on Tournament History, it will not load anything. Instead I just get a "wheel" icon spinning endlessly.

Running Mac OS 10.12.4. RPS username karen-keyes-test.

Thank you,
Karen Keyes

<img width="1168" alt="screen shot 2017-09-13 at 3 31 43 pm" src="https://user-images.githubusercontent.com/1774215/30394194-bf409992-9898-11e7-865c-22ae2519af4e.png">

**Comment by pacatum** [comment]
Fixed in https://github.com/pacatum/Helmbet-RPS/releases/tag/v0.2b
