### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by kstkeyes** [pacatum/Helmbet-RPS#9]
Grammatical error (see screenshot attached)

Should read:

The total added players has to be equal or greater than the number of players in a tournament.
<img width="248" alt="screen shot 2017-09-13 at 3 40 01 pm" src="https://user-images.githubusercontent.com/1774215/30394620-f7d62e1a-9899-11e7-8419-cc603155e65f.png">

**Comment by pacatum** [comment]
Thanks for the feedback. Issue will be fixed in next version.

**Comment by pacatum** [comment]
Fixed in https://github.com/pacatum/Helmbet-RPS/releases/tag/v0.2b
